import Head from "next/head";
import About from "../components/home/about.component";
import Appointment from "../components/home/appointment.component";
import Banner from "../components/home/banner.component";
import Contact from "../components/home/contact.component";
import Services from "../components/home/services.component";
import WhatsappIcon from "../components/ui/whatsapp-icon.component";

export default function Home() {
  return (
    <>
      <Head>
        <title>Salud empresarial | Aptus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />

      <About />

      <Services />
      <Appointment />

      <div className="info-banner">
        <div className="container">
          <img src="/tecuida/images/positive.webp" alt="Importante" width={175} height={175} className="mr-3" />
          <div className="text-white mt-2">
            <h3 className="text">
              <strong>Recuerda</strong>
            </h3>
            <p>Para ser atendido en nuestras sedes es indispensable presentar el DNI o documento de identificación y mantener siempre su mascarilla puesta.</p>
          </div>
        </div>
      </div>

      <Contact />

      <WhatsappIcon />
    </>
  );
}
