import Head from 'next/head';
import About from '../components/home/about.component';
import Appointment from '../components/home/appointment.component';
import Banner from '../components/home/banner.component';
import Contact from '../components/home/contact.component';
import Services from '../components/home/services.component';
import WhatsappIcon from '../components/ui/whatsapp-icon.component';
import { GoogleReCaptchaProvider } from 'react-google-recaptcha-v3';
import { Modal } from 'react-bootstrap';
import { useLayoutEffect, useState } from 'react';

export default function Home() {
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);

  useLayoutEffect(() => {
    setTimeout(() => setShow(true), 1500);
  }, []);

  return (
    <>
      <Head>
        <title>Salud empresarial | Aptus</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Banner />

      <About />

      <Services />

      <GoogleReCaptchaProvider
        reCaptchaKey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        scriptProps={{
          async: false, // optional, default to false,
          defer: true, // optional, default to false
          appendTo: 'body', // optional, default to "head", can be "head" or "body",
          nonce: undefined,
        }}
      >
        <Appointment />
      </GoogleReCaptchaProvider>

      <div className='info-banner'>
        <div className='container'>
          <img src='/tecuida/images/positive.webp' alt='Importante' width={175} height={175} className='mr-3' />
          <div className='text-white mt-2'>
            <h3 className='text'>
              <strong>Recuerda</strong>
            </h3>
            <p>Para ser atendido en nuestras sedes es indispensable presentar el DNI o documento de identificación y mantener siempre su mascarilla puesta.</p>
          </div>
        </div>
      </div>

      <Contact />

      <WhatsappIcon />

      <Modal show={show} onHide={handleClose}>
        <a className='d-block w-100 h-100' href='https://bit.ly/3E6ih8I' target='_blank' rel='noreferrer'>
          <div style={{ width: '100%', maxWidth: 'max-content', height: '100%', maxHeight: '30rem', margin: 'auto', backgroundColor: '#fff', borderRadius: 12 }}>
            <img src='/tecuida/images/popup.webp' width='100%' height='100%' style={{ objectFit: 'contain' }} />
          </div>
        </a>
      </Modal>
    </>
  );
}
